---
- include: repos.yml

- include: fips.yml
  when:
  - grub2_enable_fips_mode | bool

- include: audit.yml
- include: disable.yml
- include: install.yml
- include: locale.yml
- include: misc.yml
- include: pam.yml
- include: permissions.yml
- include: ssh.yml
- include: tcp.yml
