---
- include_tasks: audit.yml
- include_tasks: disable.yml
- include_tasks: fips.yml
  when:
  - grub2_enable_fips_mode | bool
- include_tasks: install.yml
- include_tasks: misc.yml
- include_tasks: pam.yml
- include_tasks: permissions.yml
- include_tasks: repos.yml
- include_tasks: ssh.yml
- include_tasks: tcp.yml
