---
- name: Disable SELinux
  selinux:
    state: disabled
  when: not selinux_state

- name: Configure SELinux state and policy
  selinux:
    policy: "{{ var_selinux_policy_name }}"
    state: "{{ var_selinux_state }}"
  when:
  - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
  - selinux_state | bool
  - selinux_policytype | bool
  - restrict_strategy | bool
  - high_severity | bool
  - low_disruption | bool
  - low_complexity | bool
  tags:
  - selinux_state
  - high_severity
  - restrict_strategy
  - low_complexity
  - low_disruption
  - CCE-27334-2
  - NIST-800-53-AC-3
  - NIST-800-53-AC-3(3)(a)
  - NIST-800-53-AU-9
  - NIST-800-53-SC-7(21)
  - NIST-800-171-3.1.2
  - NIST-800-171-3.7.2
  - DISA-STIG-RHEL-07-020210
